### ISSUE TITLE
Not working on OS X

### ISSUE THREAD

**Issue by jernejrostan** [baixuexiyang/VUEFormatter#1]
This is the error when i try to run this package

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "VUEFormatter in /Users/{user}/Library/Application Support/Sublime Text 3/Installed Packages/VueFormatter.sublime-package", line 40, in run
  File "VUEFormatter in /Users/{user}/Library/Application Support/Sublime Text 3/Installed Packages/VueFormatter.sublime-package", line 75, in save_buffer_to_temp_file
  File "./python3.3/codecs.py", line 896, in open
NotADirectoryError: [Errno 20] Not a directory: '/Users/{user}/Library/Application Support/Sublime Text 3/Installed Packages/VueFormatter.sublime-package/.__temp__'
Package Control: No updated packages

**Comment by jernejrostan** [comment]
When i installed the package over git clone directly, it is working now

**Comment by baixuexiyang** [comment]
i found the error,  repair soon, thanks!

**Comment by diachedelic** [comment]
Still broken for me when I install with Sublime 3

**Comment by baixuexiyang** [comment]
@diachedelic please select gitHub installation
Mac

git clone https://github.com/baixuexiyang/VUEFormatter.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/VUEFormatter

Linux

git clone https://github.com/baixuexiyang/VUEFormatter.git ~/.config/sublime-text-3/Packages/VUEFormatter

Windows

git clone https://github.com/baixuexiyang/VUEFormatter.git %APPDATA%/Sublime\ Text\ 3/Packages/VUEFormatter

**Comment by diachedelic** [comment]
Works perfectly now!  Thanks

**Comment by pimboden** [comment]
Doesn't work for me : 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\{MyUser}\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\VueFormatter.sublime-package/.__temp__'

**Comment by pimboden** [comment]
Works now...
If using gitbash on windows the %APPDATA%" didn't get resolved.. had to write the complete path..

**Comment by damarawy** [comment]
I tried installing the package from Sublime but it didn't work (as mentioned above) so I did clone it from GitHub to the specified directory (for OSX). Yet I'm still unable to run the formatter because I keep getting "Node.js was not found in the default path. Please specify the location."

**Comment by hjujah** [comment]
For me no errors, just not doing anything... any advice? Tried both installation over package manager and by cloning...
