### ISSUE TITLE
不支持最新版本 sublime

### ISSUE THREAD

**Issue by xueenda** [baixuexiyang/VUEFormatter#13]
Unexpected error(<class 'AttributeError'>): 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/endaxue/Library/Application Support/Sublime Text 3/Packages/VUEFormatter/VUEFormatter.py", line 48, in run
    output = self.get_output_data(output)
  File "/Users/endaxue/Library/Application Support/Sublime Text 3/Packages/VUEFormatter/VUEFormatter.py", line 113, in get_output_data
    index = output.find(OUTPUT_VALID)
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by itibbers** [comment]
I have the same question：
Unexpected error(<class 'AttributeError'>): 'NoneType' object has no attribute 'get'

**Comment by CaledoniaProject** [comment]
这个插件已经废了，可以用 jsbeautifer 替代，https://blog.damirmiladinov.com/vuejs/beautify-vuejs.html
