### ISSUE TITLE
Not Working On Mac OS

### ISSUE THREAD

**Issue by shoyuf** [baixuexiyang/VUEFormatter#3]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "VUEFormatter in /Users/shoyuf/Library/Application Support/Sublime Text 3/Installed Packages/VueFormatter.sublime-package", line 40, in run
  File "VUEFormatter in /Users/shoyuf/Library/Application Support/Sublime Text 3/Installed Packages/VueFormatter.sublime-package", line 75, in save_buffer_to_temp_file
  File "./python3.3/codecs.py", line 896, in open
NotADirectoryError: [Errno 20] Not a directory: '/Users/shoyuf/Library/Application Support/Sublime Text 3/Installed Packages/VueFormatter.sublime-package/.__temp__'

python error or node.js error?

**Comment by baixuexiyang** [comment]
i'm sorry, the installation path for the official download has problems and has been fed back to them. You can install it via GitHub.
`git clone https://github.com/baixuexiyang/VUEFormatter.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/VUEFormatter`
