### ISSUE TITLE
doens't work on windows

### ISSUE THREAD

**Issue by f-w** [baixuexiyang/VUEFormatter#7]
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\VueFormatter.sublime-package/.__temp__'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "VUEFormatter in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\VueFormatter.sublime-package", line 40, in run
  File "VUEFormatter in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\VueFormatter.sublime-package", line 75, in save_buffer_to_temp_file
  File "./python3.3/codecs.py", line 896, in open
```

**Comment by baixuexiyang** [comment]
i'm sorry, the installation path for the official download has problems and has been fed back to them. You can install it via GitHub.
git clone https://github.com/baixuexiyang/VUEFormatter.git %APPDATA%/Sublime\ Text\ 3/Packages/VUEFormatter
